# Generated by Django 2.1.5 on 2019-01-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accesstoken',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clientkey',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clientsecret',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expiresin',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refreshtoken',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
