# Generated by Django 2.1.5 on 2019-01-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190126_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiresin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timecreated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
