# Generated by Django 2.1.5 on 2019-03-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190305_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='jobImages'),
        ),
    ]
