# Generated by Django 2.1.5 on 2019-03-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='job_pictures'),
        ),
    ]
