# Generated by Django 2.1.5 on 2019-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190328_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='para1value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='para2value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
